<table border=0 cellspacing=0 cellpadding=0 style="width:;" >
<tr style="text-align:center;">
	<td align="center" style="width:90px;" >
	<input style="cursor:hand;width:100%;background-color:'#d3d3d3';" type="button"  name="wk1" value="新增工作" onclick="parent.content.location.href='wk_add.asp'" onmouseover="javascript:this.style.background='#FFd700';" onmouseout="javascript:this.style.background='#d3d3d3';">
	</td>
	<td align="center" style="width:90px;" >
	<input style="cursor:hand;width:100%;background-color:'#d3d3d3';" type="button"  name="wk2" value="執行工作" onclick="parent.content.location.href='wk_lst_doing.asp'" onmouseover="javascript:this.style.background='#FFd700';" onmouseout="javascript:this.style.background='#d3d3d3';">
	</td>
	<td align="center" style="width:90px;" >
	<input style="cursor:hand;width:100%;background-color:'#ffefd5';" type="button" name="wk6" value="專案工作" onclick="parent.content.location.href='wk_pj_list.asp'" onmouseover="javascript:this.style.background='#FFd700';" onmouseout="javascript:this.style.background='#ffefd5';">
	</td>
	<td align="center" style="width:90px;" >
	<input style="cursor:hand;width:100%;background-color:'#d3d3d3';" type="button"  name="wk3" value="預計工作" onclick="parent.content.location.href='wk_lst_undo.asp'" onmouseover="javascript:this.style.background='#FFd700';" onmouseout="javascript:this.style.background='#d3d3d3';">
	</td>
	<td align="center" style="width:90px;" >
	<input style="cursor:hand;width:100%;background-color:'#d3d3d3';" type="button"  name="wk4" value="完成工作" onclick="parent.content.location.href='wk_lst_done.asp'" onmouseover="javascript:this.style.background='#FFd700';" onmouseout="javascript:this.style.background='#d3d3d3';">
	</td>
	<td align="center" style="width:90px;" >
	<input style="cursor:hand;width:100%;background-color:'#ffe4e1';" type="button"  name="wk5" value="工作查詢" onclick="parent.content.location.href='wk_query.asp'" onmouseover="javascript:this.style.background='#FFd700';" onmouseout="javascript:this.style.background='#ffe4e1';">
	</td>
	<td align="center" style="width:90px;" >
	<input style="cursor:hand;width:100%;background-color:'#ffefd5';" type="button"  name="wk8" value="未完成日曆" onclick="parent.content.location.href='wk_calendar_all.asp'" onmouseover="javascript:this.style.background='#FFd700';" onmouseout="javascript:this.style.background='#ffefd5';">
	</td>
	<td align="center" style="width:90px;" >
	<input style="cursor:hand;width:100%;background-color:'#ffefd5';" type="button"  name="wk9" value="完成日曆" onclick="parent.content.location.href='wk_calendar_alldone.asp'" onmouseover="javascript:this.style.background='#FFd700';" onmouseout="javascript:this.style.background='#ffefd5';">
	</td>
	<td align="center" style="width:90px;" >
	<input style="cursor:hand;width:100%;background-color:'#ffe4e1';" type="button"  name="wk5" value="後台管理" onclick="parent.content.location.href='2_admin_main.asp'" onmouseover="javascript:this.style.background='#FFd700';" onmouseout="javascript:this.style.background='#ffe4e1';">
	</td>

</tr>
</table>
