<center>
<table border=0 cellspacing=0 cellpadding=0>
<col span=3 style="width:100px;text-align:center;">
<tr >	
	<td width=120 align=center>
		<input type=submit name="editok" value="確定修改" style="cursor:hand;background-color:'#d3d3d3';color:blue;width:100%;" onmouseover="javascript:this.style.background='#FFd700';" onmouseout="javascript:this.style.background='#d3d3d3';">
	</td>
	<td width=120 align=center>
		<input type=reset name="clear" value="清除資料" style="cursor:hand;background-color:'#d3d3d3';color:blue;width:100%;" onmouseover="javascript:this.style.background='#FFd700';" onmouseout="javascript:this.style.background='#d3d3d3';">
	</td>
	<td width=120 align=center>
		<input type=button name="goback1" value="回上一頁" onclick="history.back()" style="cursor:hand;background-color:'#d3d3d3';color:blue;width:100%;" onmouseover="javascript:this.style.background='#FFd700';" onmouseout="javascript:this.style.background='#d3d3d3';">
	</td>
</tr>
</table>
</center>
